// AUTO-GENERATED from /content/words.json by content/gen_data.py — do not hand-edit.
// Pronunciation tuning lives in words.json `spoken`/rime strings.

export const ONSETS = {
  b: { spoken: 'buh' },
  c: { spoken: 'kuh' },
  d: { spoken: 'duh' },
  f: { spoken: 'fuh' },
  g: { spoken: 'guh' },
  h: { spoken: 'huh' },
  j: { spoken: 'juh' },
  k: { spoken: 'kuh' },
  l: { spoken: 'luh' },
  m: { spoken: 'muh' },
  n: { spoken: 'nuh' },
  p: { spoken: 'puh' },
  r: { spoken: 'ruh' },
  s: { spoken: 'suh' },
  t: { spoken: 'tuh' },
  v: { spoken: 'vuh' },
  w: { spoken: 'wuh' },
  y: { spoken: 'yuh' },
  z: { spoken: 'zuh' },
};

export const RIMES = {
  at: { spoken: 'at' },
  an: { spoken: 'an' },
  ap: { spoken: 'ap' },
  ag: { spoken: 'ag' },
  am: { spoken: 'am' },
  ad: { spoken: 'ad' },
  ab: { spoken: 'ab' },
  ax: { spoken: 'acks' },
  ak: { spoken: 'ack' },
  ed: { spoken: 'ed' },
  eg: { spoken: 'egg' },
  em: { spoken: 'em' },
  en: { spoken: 'en' },
  et: { spoken: 'et' },
  eb: { spoken: 'ebb' },
  ig: { spoken: 'ig' },
  in: { spoken: 'in' },
  ip: { spoken: 'ip' },
  it: { spoken: 'it' },
  ix: { spoken: 'icks' },
  ib: { spoken: 'ib' },
  id: { spoken: 'id' },
  og: { spoken: 'og' },
  op: { spoken: 'op' },
  ot: { spoken: 'ot' },
  ox: { spoken: 'ox' },
  ob: { spoken: 'ob' },
  od: { spoken: 'odd' },
  om: { spoken: 'om' },
  un: { spoken: 'un' },
  up: { spoken: 'up' },
  ug: { spoken: 'ug' },
  ub: { spoken: 'ub' },
  ud: { spoken: 'udd' },
  um: { spoken: 'um' },
  ut: { spoken: 'ut' },
  us: { spoken: 'us' },
};

export const WORDS = [
  { word: 'cat', onset: 'c', rime: 'at', char: '🐈', animal: true },
  { word: 'hat', onset: 'h', rime: 'at', char: '🎩', animal: false },
  { word: 'bat', onset: 'b', rime: 'at', char: '🦇', animal: true },
  { word: 'rat', onset: 'r', rime: 'at', char: '🐀', animal: true },
  { word: 'mat', onset: 'm', rime: 'at', char: '🟫', animal: false },
  { word: 'fat', onset: 'f', rime: 'at', char: '🐹', animal: true },
  { word: 'pat', onset: 'p', rime: 'at', char: '✋', animal: false },
  { word: 'sat', onset: 's', rime: 'at', char: '🧎', animal: false },
  { word: 'man', onset: 'm', rime: 'an', char: '👨', animal: false },
  { word: 'van', onset: 'v', rime: 'an', char: '🚐', animal: false },
  { word: 'pan', onset: 'p', rime: 'an', char: '🍳', animal: false },
  { word: 'fan', onset: 'f', rime: 'an', char: '🌀', animal: false },
  { word: 'can', onset: 'c', rime: 'an', char: '🥫', animal: false },
  { word: 'ran', onset: 'r', rime: 'an', char: '🏃', animal: false },
  { word: 'map', onset: 'm', rime: 'ap', char: '🗺️', animal: false },
  { word: 'cap', onset: 'c', rime: 'ap', char: '🧢', animal: false },
  { word: 'nap', onset: 'n', rime: 'ap', char: '😴', animal: false },
  { word: 'tap', onset: 't', rime: 'ap', char: '🚰', animal: false },
  { word: 'zap', onset: 'z', rime: 'ap', char: '⚡', animal: false },
  { word: 'lap', onset: 'l', rime: 'ap', char: '🧓', animal: false },
  { word: 'yap', onset: 'y', rime: 'ap', char: '🐕', animal: true },
  { word: 'bag', onset: 'b', rime: 'ag', char: '🎒', animal: false },
  { word: 'tag', onset: 't', rime: 'ag', char: '🏷️', animal: false },
  { word: 'rag', onset: 'r', rime: 'ag', char: '🧽', animal: false },
  { word: 'wag', onset: 'w', rime: 'ag', char: '🐕', animal: true },
  { word: 'ham', onset: 'h', rime: 'am', char: '🍖', animal: false },
  { word: 'jam', onset: 'j', rime: 'am', char: '🍓', animal: false },
  { word: 'ram', onset: 'r', rime: 'am', char: '🐏', animal: true },
  { word: 'dam', onset: 'd', rime: 'am', char: '🦫', animal: true },
  { word: 'yam', onset: 'y', rime: 'am', char: '🍠', animal: false },
  { word: 'dad', onset: 'd', rime: 'ad', char: '👨', animal: false },
  { word: 'mad', onset: 'm', rime: 'ad', char: '😠', animal: false },
  { word: 'sad', onset: 's', rime: 'ad', char: '😢', animal: false },
  { word: 'pad', onset: 'p', rime: 'ad', char: '📝', animal: false },
  { word: 'cab', onset: 'c', rime: 'ab', char: '🚕', animal: false },
  { word: 'wax', onset: 'w', rime: 'ax', char: '🕯️', animal: false },
  { word: 'yak', onset: 'y', rime: 'ak', char: '🐃', animal: true },
  { word: 'bed', onset: 'b', rime: 'ed', char: '🛏️', animal: false },
  { word: 'red', onset: 'r', rime: 'ed', char: '🍎', animal: false },
  { word: 'fed', onset: 'f', rime: 'ed', char: '🍼', animal: false },
  { word: 'wed', onset: 'w', rime: 'ed', char: '💒', animal: false },
  { word: 'leg', onset: 'l', rime: 'eg', char: '🦵', animal: false },
  { word: 'peg', onset: 'p', rime: 'eg', char: '🪵', animal: false },
  { word: 'beg', onset: 'b', rime: 'eg', char: '🐶', animal: true },
  { word: 'gem', onset: 'g', rime: 'em', char: '💎', animal: false },
  { word: 'hen', onset: 'h', rime: 'en', char: '🐔', animal: true },
  { word: 'pen', onset: 'p', rime: 'en', char: '🖊️', animal: false },
  { word: 'ten', onset: 't', rime: 'en', char: '🔟', animal: false },
  { word: 'den', onset: 'd', rime: 'en', char: '🦊', animal: true },
  { word: 'jet', onset: 'j', rime: 'et', char: '✈️', animal: false },
  { word: 'net', onset: 'n', rime: 'et', char: '🥅', animal: false },
  { word: 'pet', onset: 'p', rime: 'et', char: '🐾', animal: false },
  { word: 'vet', onset: 'v', rime: 'et', char: '🩺', animal: false },
  { word: 'wet', onset: 'w', rime: 'et', char: '💦', animal: false },
  { word: 'web', onset: 'w', rime: 'eb', char: '🕸️', animal: false },
  { word: 'pig', onset: 'p', rime: 'ig', char: '🐷', animal: true },
  { word: 'wig', onset: 'w', rime: 'ig', char: '👩‍🦰', animal: false },
  { word: 'dig', onset: 'd', rime: 'ig', char: '⛏️', animal: false },
  { word: 'fig', onset: 'f', rime: 'ig', char: '🟣', animal: false },
  { word: 'big', onset: 'b', rime: 'ig', char: '🐘', animal: true },
  { word: 'rig', onset: 'r', rime: 'ig', char: '🚚', animal: false },
  { word: 'jig', onset: 'j', rime: 'ig', char: '🎶', animal: false },
  { word: 'pin', onset: 'p', rime: 'in', char: '📌', animal: false },
  { word: 'fin', onset: 'f', rime: 'in', char: '🐟', animal: false },
  { word: 'bin', onset: 'b', rime: 'in', char: '🗑️', animal: false },
  { word: 'tin', onset: 't', rime: 'in', char: '🥫', animal: false },
  { word: 'win', onset: 'w', rime: 'in', char: '🏆', animal: false },
  { word: 'lip', onset: 'l', rime: 'ip', char: '👄', animal: false },
  { word: 'zip', onset: 'z', rime: 'ip', char: '🧥', animal: false },
  { word: 'sip', onset: 's', rime: 'ip', char: '🥤', animal: false },
  { word: 'dip', onset: 'd', rime: 'ip', char: '🥣', animal: false },
  { word: 'rip', onset: 'r', rime: 'ip', char: '📄', animal: false },
  { word: 'sit', onset: 's', rime: 'it', char: '🪑', animal: false },
  { word: 'kit', onset: 'k', rime: 'it', char: '🧰', animal: false },
  { word: 'lit', onset: 'l', rime: 'it', char: '🕯️', animal: false },
  { word: 'fit', onset: 'f', rime: 'it', char: '💪', animal: false },
  { word: 'six', onset: 's', rime: 'ix', char: '6️⃣', animal: false },
  { word: 'mix', onset: 'm', rime: 'ix', char: '🥣', animal: false },
  { word: 'fix', onset: 'f', rime: 'ix', char: '🔧', animal: false },
  { word: 'bib', onset: 'b', rime: 'ib', char: '🍼', animal: false },
  { word: 'lid', onset: 'l', rime: 'id', char: '🫙', animal: false },
  { word: 'kid', onset: 'k', rime: 'id', char: '🐐', animal: true },
  { word: 'hid', onset: 'h', rime: 'id', char: '🙈', animal: false },
  { word: 'dog', onset: 'd', rime: 'og', char: '🐕', animal: true },
  { word: 'log', onset: 'l', rime: 'og', char: '🪵', animal: false },
  { word: 'fog', onset: 'f', rime: 'og', char: '🌫️', animal: false },
  { word: 'hog', onset: 'h', rime: 'og', char: '🐗', animal: true },
  { word: 'jog', onset: 'j', rime: 'og', char: '🏃', animal: false },
  { word: 'cog', onset: 'c', rime: 'og', char: '⚙️', animal: false },
  { word: 'top', onset: 't', rime: 'op', char: '🔝', animal: false },
  { word: 'mop', onset: 'm', rime: 'op', char: '🧹', animal: false },
  { word: 'pop', onset: 'p', rime: 'op', char: '🍭', animal: false },
  { word: 'hop', onset: 'h', rime: 'op', char: '🐰', animal: false },
  { word: 'cop', onset: 'c', rime: 'op', char: '👮', animal: false },
  { word: 'pot', onset: 'p', rime: 'ot', char: '🍲', animal: false },
  { word: 'hot', onset: 'h', rime: 'ot', char: '🔥', animal: false },
  { word: 'cot', onset: 'c', rime: 'ot', char: '🛏️', animal: false },
  { word: 'dot', onset: 'd', rime: 'ot', char: '⚫', animal: false },
  { word: 'box', onset: 'b', rime: 'ox', char: '📦', animal: false },
  { word: 'fox', onset: 'f', rime: 'ox', char: '🦊', animal: true },
  { word: 'cob', onset: 'c', rime: 'ob', char: '🌽', animal: false },
  { word: 'sob', onset: 's', rime: 'ob', char: '😭', animal: false },
  { word: 'pod', onset: 'p', rime: 'od', char: '🫛', animal: false },
  { word: 'rod', onset: 'r', rime: 'od', char: '🎣', animal: false },
  { word: 'cod', onset: 'c', rime: 'od', char: '🐟', animal: false },
  { word: 'nod', onset: 'n', rime: 'od', char: '🙂', animal: false },
  { word: 'mom', onset: 'm', rime: 'om', char: '👩', animal: false },
  { word: 'sun', onset: 's', rime: 'un', char: '🌞', animal: false },
  { word: 'run', onset: 'r', rime: 'un', char: '🏃', animal: false },
  { word: 'bun', onset: 'b', rime: 'un', char: '🍞', animal: false },
  { word: 'fun', onset: 'f', rime: 'un', char: '🎉', animal: false },
  { word: 'cup', onset: 'c', rime: 'up', char: '☕', animal: false },
  { word: 'pup', onset: 'p', rime: 'up', char: '🐶', animal: true },
  { word: 'bug', onset: 'b', rime: 'ug', char: '🐛', animal: true },
  { word: 'rug', onset: 'r', rime: 'ug', char: '🟥', animal: false },
  { word: 'mug', onset: 'm', rime: 'ug', char: '☕', animal: false },
  { word: 'hug', onset: 'h', rime: 'ug', char: '🤗', animal: false },
  { word: 'jug', onset: 'j', rime: 'ug', char: '🥛', animal: false },
  { word: 'pug', onset: 'p', rime: 'ug', char: '🐶', animal: true },
  { word: 'tug', onset: 't', rime: 'ug', char: '🚢', animal: false },
  { word: 'dug', onset: 'd', rime: 'ug', char: '🕳️', animal: false },
  { word: 'tub', onset: 't', rime: 'ub', char: '🛁', animal: false },
  { word: 'cub', onset: 'c', rime: 'ub', char: '🐻', animal: true },
  { word: 'sub', onset: 's', rime: 'ub', char: '🟡', animal: false },
  { word: 'mud', onset: 'm', rime: 'ud', char: '🟤', animal: false },
  { word: 'bud', onset: 'b', rime: 'ud', char: '🌷', animal: false },
  { word: 'gum', onset: 'g', rime: 'um', char: '🫧', animal: false },
  { word: 'hum', onset: 'h', rime: 'um', char: '🎵', animal: false },
  { word: 'yum', onset: 'y', rime: 'um', char: '😋', animal: false },
  { word: 'nut', onset: 'n', rime: 'ut', char: '🥜', animal: false },
  { word: 'hut', onset: 'h', rime: 'ut', char: '🛖', animal: false },
  { word: 'cut', onset: 'c', rime: 'ut', char: '✂️', animal: false },
  { word: 'bus', onset: 'b', rime: 'us', char: '🚌', animal: false },
];

// Real words a child can build from the tiles but that have no picture card.
// Dictionary-checked and safety-filtered. They get a warm 'real word!' response.
export const BONUS_WORDS = [
  'bap', 'bet', 'bop', 'bot', 'but', 'cad', 'cag', 'cox', 'dan', 'din', 'dop', 'fad', 'fam',
  'fop', 'fot', 'fug', 'gud', 'hap', 'het', 'hub', 'hud', 'jed', 'jut', 'kin', 'lop', 'lot',
  'mag', 'mam', 'min', 'mum', 'ned', 'pam', 'ped', 'pip', 'pox', 'rad', 'san', 'sup', 'ted',
];

export const FREEPLAY_SETS = [
  { onsets: ['c', 'h', 'b', 'm'], rimes: ['at', 'ap', 'ag'] },
  { onsets: ['m', 'v', 'p', 'f'], rimes: ['an', 'am', 'ad'] },
  { onsets: ['r', 'c', 'd', 's'], rimes: ['at', 'an', 'ad'] },
  { onsets: ['h', 'p', 't', 'n'], rimes: ['en', 'et', 'ed'] },
  { onsets: ['b', 'j', 'v', 'w'], rimes: ['et', 'ed', 'eg'] },
  { onsets: ['p', 'w', 'd', 'b'], rimes: ['ig', 'in', 'ip'] },
  { onsets: ['s', 'f', 'm', 'k'], rimes: ['it', 'ix', 'in'] },
  { onsets: ['d', 'l', 'f', 'h'], rimes: ['og', 'op', 'ot'] },
  { onsets: ['b', 'f', 'c', 'p'], rimes: ['ox', 'ot', 'op'] },
  { onsets: ['s', 'r', 'b', 'f'], rimes: ['un', 'ug', 'up'] },
  { onsets: ['m', 'h', 'j', 'c'], rimes: ['ug', 'ub', 'ut'] },
  { onsets: ['m', 'b', 'g', 'h'], rimes: ['ud', 'um', 'ut'] },
];

export const PHRASES = {
  celebrate: ['You made {word}!', 'Hooray! {word}!', 'Wow, you built {word}!', 'Yay! {word}!'],
  bonus: ['{word}! That is a real word too!', 'Ooh, {word} is a word! Can you find one with a picture?'],
  silly: ['{blend}! What a silly sound! Try another one.', 'Hee hee, {blend}? That is so silly! Try again.'],
  guidedPrompt: ['Can you make {word}?', 'Let\u2019s build {word}!'],
  mysteryPrompt: ['Mystery word! Listen. {onset}. {rime}. What does it make?'],
};
